// Candyaura premium UX layer — loaded only if you include <script src="upgrade.js"></script> before </body>.
(function(){
 const products={
  'Strawberry Bliss':{price:450,desc:'Bright strawberry candy with a playful finish.',emoji:'🍓'},
  'Rainbow Gummies':{price:550,desc:'Soft colourful gummies for a cheerful break.',emoji:'🍬'},
  'Chocolate Dream':{price:650,desc:'Chocolatey bites for a rich indulgent mood.',emoji:'🍫'},
  'Candy Pop Jar':{price:600,desc:'A colourful mix made for beautiful gifting.',emoji:'🍭'},
  'Berry Mix':{price:500,desc:'A juicy berry-inspired mix for fruity lovers.',emoji:'🫐'},
  'Caramel Bites':{price:700,desc:'Sweet caramel-style treats with a rich finish.',emoji:'🍯'},
  'Lollipop Party':{price:550,desc:'A colourful selection made for celebrations.',emoji:'🍭'},
  'Sweet Gift Box':{price:900,desc:'A ready-to-gift candy selection for special moments.',emoji:'🎁'}
 };
 const style=document.createElement('style');style.textContent=`.ca-wish{position:absolute;right:12px;top:12px;border:0;border-radius:50%;width:34px;height:34px;background:#fff;color:#d94f87;box-shadow:0 5px 15px #0001;cursor:pointer;font-size:17px;z-index:3}.ca-wish.on{background:#d94f87;color:#fff}.ca-modal{position:fixed;inset:0;background:#24171d99;z-index:100;display:flex;align-items:center;justify-content:center;padding:16px;opacity:0;pointer-events:none;transition:.2s}.ca-modal.on{opacity:1;pointer-events:auto}.ca-box{width:min(520px,100%);background:#fff;border-radius:28px;padding:28px;box-shadow:0 30px 90px #0004;position:relative}.ca-x{position:absolute;right:16px;top:16px;border:0;background:#f7eef2;border-radius:50%;width:36px;height:36px;cursor:pointer}.ca-big{font-size:88px;text-align:center;background:linear-gradient(145deg,#fff,#fff0f6);border-radius:22px;padding:25px}.ca-box h3{font:800 31px 'Playfair Display',serif;margin:20px 0 6px}.ca-box p{color:#756970;font-size:12px;line-height:1.8}.ca-price{font-weight:800;font-size:20px;margin:15px 0}.ca-offer{margin-top:12px;padding:14px;border:1px dashed #d94f87;border-radius:15px;background:#fff8fb;font-size:11px}.ca-badge{position:fixed;left:18px;bottom:18px;z-index:30;background:#291920;color:#fff;border-radius:24px;padding:11px 15px;font-size:10px;box-shadow:0 10px 30px #0003}.ca-badge b{color:#f7b8cf}.ca-strip{background:#fff0f6;border-block:1px solid #eadfe3;padding:12px;text-align:center;font-size:10px;font-weight:800;letter-spacing:.08em;color:#a73c69}.ca-wishlist-title{margin:0 0 15px;font:800 27px 'Playfair Display',serif}`;document.head.appendChild(style);
 document.querySelectorAll('.product').forEach(card=>{const h=card.querySelector('h3');if(!h)return;const name=h.textContent;const b=document.createElement('button');b.className='ca-wish';b.innerHTML='♡';b.title='Add to wishlist';b.onclick=e=>{e.stopPropagation();b.classList.toggle('on');b.innerHTML=b.classList.contains('on')?'♥':'♡';localStorage.setItem('wish_'+name,b.classList.contains('on'));};if(localStorage.getItem('wish_'+name)==='true'){b.classList.add('on');b.innerHTML='♥'}card.querySelector('.media').appendChild(b);card.onclick=e=>{if(e.target.closest('button'))return;open(name)};});
 const modal=document.createElement('div');modal.className='ca-modal';modal.innerHTML='<div class="ca-box"><button class="ca-x">✕</button><div class="ca-big" id="caEmoji"></div><h3 id="caName"></h3><p id="caDesc"></p><div class="ca-price" id="caPrice"></div><div class="ca-offer">🎁 <b>Gift idea:</b> Pair any two jars for a sweet surprise.</div><button class="btn primary" id="caAdd" style="width:100%;margin-top:16px">Add to cart →</button></div>';document.body.appendChild(modal);modal.querySelector('.ca-x').onclick=()=>modal.classList.remove('on');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('on')};function open(n){const p=products[n];if(!p)return;document.getElementById('caEmoji').textContent=p.emoji;document.getElementById('caName').textContent=n;document.getElementById('caDesc').textContent=p.desc;document.getElementById('caPrice').textContent='Rs. '+p.price.toLocaleString()+' / jar';document.getElementById('caAdd').onclick=()=>{if(typeof addToCart==='function')addToCart(n,p.price);modal.classList.remove('on')};modal.classList.add('on')}
 const strip=document.createElement('div');strip.className='ca-strip';strip.textContent='🎀 TODAY’S SWEET DEAL · Buy 2 jars and get a special gift-ready packing upgrade';const shop=document.getElementById('shop');if(shop)shop.parentNode.insertBefore(strip,shop);
 const badge=document.createElement('div');badge.className='ca-badge';badge.innerHTML='✨ <b>Candyaura</b> · Sweetness, reimagined';document.body.appendChild(badge);
})();
