const orderEnhancer = `
<style>
#ca-order-fab{position:fixed;right:18px;bottom:18px;z-index:9998;background:#f44d98;color:#fff;border:0;border-radius:999px;padding:14px 18px;font:800 13px Arial,sans-serif;box-shadow:0 12px 30px #0003;cursor:pointer}#ca-order-fab b{background:#180d18;padding:2px 7px;border-radius:99px;margin-left:5px}#ca-modal{position:fixed;inset:0;background:#180d1888;z-index:9999;display:none;align-items:center;justify-content:center;padding:16px}#ca-modal.open{display:flex}.ca-box{width:min(460px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:22px;box-shadow:0 25px 70px #0004;font:14px Arial,sans-serif;color:#180d18}.ca-box h2{margin:0 0 5px;font:800 28px Georgia,serif}.ca-sub{color:#777;margin-bottom:15px;font-size:12px}.ca-items{background:#fff8fb;border:1px solid #eadfe4;border-radius:14px;padding:12px;margin-bottom:14px}.ca-item{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #eadfe4}.ca-item:last-child{border-bottom:0}.ca-box label{display:block;font-weight:700;font-size:12px;margin:10px 0 5px}.ca-box input{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid #ddd;border-radius:10px;outline:0}.ca-total{margin-top:14px;border-top:1px solid #eee;padding-top:12px;line-height:1.8}.ca-actions{display:flex;gap:8px;margin-top:15px}.ca-actions button{flex:1;border:0;border-radius:999px;padding:12px;font-weight:800;cursor:pointer}.ca-cancel{background:#f5eef2}.ca-submit{background:#f44d98;color:#fff}.ca-msg{font-size:12px;color:#777;margin-top:8px}.ca-close{float:right;border:0;background:#f5eef2;border-radius:50%;width:34px;height:34px;cursor:pointer}
</style>
<button id="ca-order-fab">📦 Order <b id="ca-count">0</b></button>
<div id="ca-modal"><div class="ca-box"><button class="ca-close" id="ca-close">×</button><h2>Your Order</h2><div class="ca-sub">Delivery charges calculated by distance</div><div id="ca-items" class="ca-items"></div><label>Full name</label><input id="ca-name" placeholder="Your name"><label>Phone</label><input id="ca-phone" placeholder="03XXXXXXXXX" inputmode="tel"><label>Delivery address</label><input id="ca-address" placeholder="Complete address"><label>Distance (km)</label><input id="ca-distance" type="number" min="0" step="0.1" placeholder="e.g. 5"><div class="ca-total"><div>Subtotal: <b id="ca-subtotal">Rs 0</b></div><div>Delivery: <b id="ca-delivery">Rs 0</b></div><div>Total: <b id="ca-total">Rs 0</b></div><div class="ca-msg">Rs 80 for first 5 km, then Rs 80 for every additional 5 km.</div></div><div class="ca-actions"><button class="ca-cancel" id="ca-cancel">Cancel</button><button class="ca-submit" id="ca-submit">Place Order</button></div><div id="ca-status" class="ca-msg"></div></div></div>
<script>
(()=>{const cart=[];const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function add(name,price){price=Number(price)||0;let x=cart.find(i=>i.name===name&&i.price===price);if(x)x.qty++;else cart.push({name,price,qty:1});render();}
function render(){q('#ca-count').textContent=cart.reduce((a,i)=>a+i.qty,0);const box=q('#ca-items');box.innerHTML=cart.length?cart.map(i=>'<div class="ca-item"><span>'+esc(i.name)+' × '+i.qty+'</span><b>Rs '+(i.price*i.qty)+'</b></div>').join(''):'<div style="color:#777;text-align:center">Add products to your cart first.</div>';calc();}
function calc(){const sub=cart.reduce((a,i)=>a+i.price*i.qty,0);const d=Number(q('#ca-distance')?.value||0);const fee=d>0?Math.ceil(d/5)*80:0;q('#ca-subtotal').textContent='Rs '+sub;q('#ca-delivery').textContent='Rs '+fee;q('#ca-total').textContent='Rs '+(sub+fee);return{sub,fee,total:sub+fee,distance:d};}
function open(){render();q('#ca-modal').classList.add('open');}function close(){q('#ca-modal').classList.remove('open');q('#ca-status').textContent='';}
document.addEventListener('click',e=>{const b=e.target.closest('.add,.order-btn');if(b){const card=b.closest('.product');if(card){const name=card.querySelector('h3')?.textContent?.trim()||'Candy';const p=card.querySelector('.price')?.textContent||'';add(name,p.replace(/[^0-9.]/g,''));}}const wa=e.target.closest('a,button');if(wa&&/whatsapp|send order/i.test(wa.textContent||'')){e.preventDefault();e.stopImmediatePropagation();open();}},true);
q('#ca-order-fab').addEventListener('click',open);q('#ca-close').addEventListener('click',close);q('#ca-cancel').addEventListener('click',close);q('#ca-distance').addEventListener('input',calc);
q('#ca-submit').addEventListener('click',async()=>{const name=q('#ca-name').value.trim(),phone=q('#ca-phone').value.trim(),address=q('#ca-address').value.trim();const {sub,fee,total,distance}=calc();if(!cart.length)return q('#ca-status').textContent='Please add at least one product.';if(!name||!phone||!address||distance<=0)return q('#ca-status').textContent='Please fill all details, including distance.';q('#ca-submit').disabled=true;q('#ca-status').textContent='Placing order…';try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:name,phone,address,distance_km:distance,items:cart,subtotal:sub,delivery_charge:fee,total})});const data=await r.json();if(!r.ok||!data.ok)throw Error(data.error||'Order failed');q('#ca-status').textContent='Order received successfully! Order #'+data.id;cart.length=0;render();}catch(e){q('#ca-status').textContent=e.message||'Could not place order.'}finally{q('#ca-submit').disabled=false;}});render();})();
</script>`;
export default {async fetch(request,env){const url=new URL(request.url);const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'};if(request.method==='OPTIONS')return new Response(null,{headers:cors});
if(url.pathname==='/api/orders'&&request.method==='POST'){try{const b=await request.json();if(!b.customer_name||!b.phone||!b.address||!Number.isFinite(Number(b.distance_km)))return Response.json({ok:false,error:'Missing order details'},{status:400,headers:cors});const r=await env.DB.prepare("INSERT INTO orders (customer_name,phone,address,distance_km,items,subtotal,delivery_charge,total,status) VALUES (?,?,?,?,?,?,?,?, 'new')").bind(b.customer_name,b.phone,b.address,Number(b.distance_km),JSON.stringify(b.items||[]),Number(b.subtotal)||0,Number(b.delivery_charge)||0,Number(b.total)||0).run();return Response.json({ok:true,id:r.meta.last_row_id},{headers:cors});}catch(e){return Response.json({ok:false,error:'Could not save order'},{status:400,headers:cors});}}
if(url.pathname==='/api/orders'&&request.method==='GET'){try{const r=await env.DB.prepare('SELECT * FROM orders ORDER BY id DESC LIMIT 100').all();return Response.json({orders:r.results||[]},{headers:cors});}catch(e){return Response.json({orders:[],error:'Could not load orders'},{status:500,headers:cors});}}
if(url.pathname.startsWith('/api/orders/')&&request.method==='PATCH'){const id=url.pathname.split('/').pop();const b=await request.json();await env.DB.prepare('UPDATE orders SET status=? WHERE id=?').bind(b.status,id).run();return Response.json({ok:true},{headers:cors});}
const res=await env.ASSETS.fetch(request);const ct=res.headers.get('content-type')||'';if(ct.includes('text/html')){let html=await res.text();html=html.replace('</body>',orderEnhancer+'</body>');return new Response(html,{status:res.status,headers:res.headers});}return res;}};
